<?php
/**
 * Advanced Custom Fields
 */

// define fields
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_654ecbda49dbc',
	'title' => 'Bio Widget',
	'fields' => array(
		array(
			'key' => 'field_654ecbdaa90b9',
			'label' => 'Page Link',
			'name' => 'page_link',
			'aria-label' => '',
			'type' => 'link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
		),
		array(
			'key' => 'field_65600437dbb32',
			'label' => 'Tooltip',
			'name' => 'enable_tooltip',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '15',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable?',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_6560046bdbb33',
			'label' => '',
			'name' => 'tooltip_text',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_65600437dbb32',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '85',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => 'Text',
			'append' => '',
		),
		array(
			'key' => 'field_656021baa158f',
			'label' => '',
			'name' => 'tooltip_timeout',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_65600437dbb32',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 15,
			'min' => 5,
			'max' => 30,
			'placeholder' => '',
			'step' => 5,
			'prepend' => 'Seconds Visible',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'user_form',
				'operator' => '==',
				'value' => 'edit',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
	'acfe_display_title' => '',
	'acfe_autosync' => '',
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
) );

	acf_add_local_field_group( array(
	'key' => 'group_654fb2afc3479',
	'title' => 'Credit',
	'fields' => array(
		array(
			'key' => 'field_654fb2afd7588',
			'label' => 'Credit',
			'name' => 'image_credit',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => 'It\'s always good to credit whoever made this.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'attachment',
				'operator' => '==',
				'value' => 'image',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => '',
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
) );

	acf_add_local_field_group( array(
	'key' => 'group_654d33026beb4',
	'title' => 'Images Options',
	'fields' => array(
		array(
			'key' => 'field_65adff76f172f',
			'label' => 'Favicon',
			'name' => 'favicon',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'Displayed in the browser tab.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'uploader' => '',
			'return_format' => 'id',
			'acfe_thumbnail' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_permissions' => '',
			'preview_size' => 'thumbnail',
			'library' => 'all',
		),
		array(
			'key' => 'field_654e55b7801b4',
			'label' => 'Icon',
			'name' => 'icon',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'Displayed on the login page.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'uploader' => '',
			'return_format' => 'id',
			'wp_object' => '',
			'acfe_thumbnail' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_permissions' => '',
			'preview_size' => 'medium',
			'library' => 'all',
		),
		array(
			'key' => 'field_654d33028a032',
			'label' => 'Logo',
			'name' => 'logo',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'Displayed in the sidebar.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'uploader' => '',
			'return_format' => 'id',
			'wp_object' => '',
			'acfe_thumbnail' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_permissions' => '',
			'preview_size' => 'medium',
			'library' => 'all',
		),
		array(
			'key' => 'field_654d33428a033',
			'label' => 'Background',
			'name' => 'background',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'Displayed in the background and login page.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'uploader' => '',
			'return_format' => 'id',
			'wp_object' => '',
			'acfe_thumbnail' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_permissions' => '',
			'preview_size' => '1536x1536',
			'library' => 'all',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'wp_options',
				'operator' => '==',
				'value' => 'general',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'tooltip',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Here you set the various images that will be displayed on the site; such as the favicon and logo.',
	'show_in_rest' => 1,
	'acfe_display_title' => 'Images',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_permissions' => '',
	'acfe_form' => 1,
	'acfe_meta' => '',
	'acfe_note' => '',
) );

	acf_add_local_field_group( array(
	'key' => 'group_65adf8746e8a8',
	'title' => 'Links',
	'fields' => array(
		array(
			'key' => 'field_65adf8743274a',
			'label' => '',
			'name' => 'links',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 1,
			'layout' => 'row',
			'pagination' => 0,
			'acfe_settings' => array(
				'65adfec048985' => array(
					'acfe_settings_location' => '',
					'acfe_settings_settings' => array(
						'65adfec348986' => array(
							'acfe_settings_setting_type' => 'hide_label',
							'acfe_settings_setting_operator' => 'true',
						),
					),
				),
			),
			'min' => 0,
			'max' => 0,
			'acfe_permissions' => '',
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_65adf8be3274b',
					'label' => 'Link',
					'name' => 'link',
					'aria-label' => '',
					'type' => 'link',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'parent_repeater' => 'field_65adf8743274a',
				),
				array(
					'key' => 'field_65adf9053274c',
					'label' => 'Icon SVG',
					'name' => 'icon_svg',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M10.59,13.41C11,13.8 11,14.44 10.59,14.83C10.2,15.22 9.56,15.22 9.17,14.83C7.22,12.88 7.22,9.71 9.17,7.76V7.76L12.71,4.22C14.66,2.27 17.83,2.27 19.78,4.22C21.73,6.17 21.73,9.34 19.78,11.29L18.29,12.78C18.3,11.96 18.17,11.14 17.89,10.36L18.36,9.88C19.54,8.71 19.54,6.81 18.36,5.64C17.19,4.46 15.29,4.46 14.12,5.64L10.59,9.17C9.41,10.34 9.41,12.24 10.59,13.41M13.41,9.17C13.8,8.78 14.44,8.78 14.83,9.17C16.78,11.12 16.78,14.29 14.83,16.24V16.24L11.29,19.78C9.34,21.73 6.17,21.73 4.22,19.78C2.27,17.83 2.27,14.66 4.22,12.71L5.71,11.22C5.7,12.04 5.83,12.86 6.11,13.65L5.64,14.12C4.46,15.29 4.46,17.19 5.64,18.36C6.81,19.54 8.71,19.54 9.88,18.36L13.41,14.83C14.59,13.66 14.59,11.76 13.41,10.59C13,10.2 13,9.56 13.41,9.17Z" /></svg>',
					'acfe_textarea_code' => 0,
					'acfe_settings' => '',
					'acfe_validate' => '',
					'maxlength' => '',
					'acfe_permissions' => '',
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
					'parent_repeater' => 'field_65adf8743274a',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'options-social',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Here you can add the various links that appear under "Connect" in the side panel.',
	'show_in_rest' => 1,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_permissions' => '',
	'acfe_form' => 1,
	'acfe_meta' => '',
	'acfe_note' => '',
) );

	acf_add_local_field_group( array(
	'key' => 'group_65b2c05080596',
	'title' => 'Login',
	'fields' => array(
		array(
			'key' => 'field_65b2c05037fe9',
			'label' => 'Headline',
			'name' => 'login_headline',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_65b2c06437fea',
			'label' => 'Description',
			'name' => 'login_description',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_textarea_code' => 0,
			'maxlength' => '',
			'rows' => '',
			'placeholder' => '',
			'new_lines' => 'wpautop',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'login',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => '',
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
) );

	acf_add_local_field_group( array(
	'key' => 'group_65adb68866304',
	'title' => 'Footer Options',
	'fields' => array(
		array(
			'key' => 'field_65526ef81b12e',
			'label' => 'Desktop',
			'name' => 'desktop_footer',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'The full footer content. Displayed on larger screens.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'wp_object' => '',
			'is_id' => 0,
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_65526f0d1b12f',
			'label' => 'Mobile',
			'name' => 'mobile_footer',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'The shortened footer content. Displayed on smaller screens.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'wp_object' => '',
			'is_id' => 0,
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'wp_options',
				'operator' => '==',
				'value' => 'general',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
	'acfe_display_title' => 'Footer',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 1,
	'acfe_meta' => '',
	'acfe_note' => '',
) );
} );

add_action( 'acf/init', function() {
	acf_add_options_page( array(
	'page_title' => 'Connections',
	'menu_slug' => 'options-social',
	'parent_slug' => 'options-general.php',
	'menu_title' => 'Connections',
	'position' => '',
	'redirect' => false,
	'update_button' => 'Save Changes',
	'updated_message' => 'Saved',
	'capability' => 'manage_options',
	'post_id' => 'wp_settings',
	'autoload' => true,
) );

	acf_add_options_page( array(
	'page_title' => 'Login',
	'menu_slug' => 'login',
	'parent_slug' => 'options-general.php',
	'position' => '',
	'redirect' => false,
) );
} );

// add location rules
// Step 1: Add a new location rule type
add_filter('acf/location/rule_types', 'my_acf_custom_location_types');
function my_acf_custom_location_types($choices) {
    // Add a new location rule under the 'Forms' category
    $choices['Forms']['wp_options'] = 'Settings Page';
    return $choices;
}

// Step 2: Define the possible values for your custom rule
add_filter('acf/location/rule_values/wp_options', 'my_acf_custom_location_values');
function my_acf_custom_location_values($choices) {
    // Define the values that your custom location can have
    $choices['general'] = 'General';
    return $choices;
}